import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from fpdf import FPDF
from datetime import datetime
import io

# --- 페이지 설정 ---
st.set_page_config(page_title="B-Balance.tech", layout="wide")

# --- 핵심 로직: 벡터 합성 ---
def calculate_analysis(df):
    if df.empty: return 0, 0
    mags = pd.to_numeric(df['Magnitude'], errors='coerce').fillna(0)
    phases = pd.to_numeric(df['Phase'], errors='coerce').fillna(0)
    rads = np.radians(phases)
    sx = np.sum(mags * np.cos(rads))
    sy = np.sum(mags * np.sin(rads))
    mag = np.hypot(sx, sy)
    ang = (np.degrees(np.atan2(sy, sx)) + 360) % 360
    return mag, ang

# --- PDF 보고서 생성 함수 ---
def generate_pdf(df, mag, ang):
    pdf = FPDF()
    pdf.add_page()
    
    # 헤더 섹션
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Blade Moment Weight Analysis Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 10, f"Generated by B-Balance.tech | Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
    pdf.ln(10)

    # 요약 정보 (Resultant)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "1. Vector Synthesis Result (Resultant)", ln=True, fill=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"- Calculated Unbalance: {mag:.6f}", ln=True)
    pdf.cell(0, 8, f"- Calculated Angle: {ang:.2f} deg", ln=True)
    pdf.cell(0, 8, f"- Total Blade Count: {len(df)}", ln=True)
    pdf.ln(5)

    # 상세 데이터 테이블
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "2. Blade Distribution Data", ln=True, fill=True)
    pdf.set_font("Helvetica", "B", 10)
    
    # 테이블 헤더
    pdf.cell(20, 8, "Pos.", border=1)
    pdf.cell(60, 8, "Serial No.", border=1)
    pdf.cell(50, 8, "Magnitude (Moment)", border=1)
    pdf.cell(50, 8, "Phase (deg)", border=1, ln=True)
    
    # 테이블 내용
    pdf.set_font("Helvetica", "", 10)
    for i, row in df.iterrows():
        pdf.cell(20, 8, str(int(i+1)), border=1)
        # 일련번호가 없으면 'N/A'로 표시
        serial = str(row['Serial']) if 'Serial' in df.columns and row['Serial'] else f"ID-{int(i+1):03d}"
        pdf.cell(60, 8, serial, border=1)
        pdf.cell(50, 8, f"{float(row['Magnitude']):.3f}", border=1)
        pdf.cell(50, 8, f"{float(row['Phase']):.3f}", border=1, ln=True)
        
    return pdf.output()

# --- UI 구성 ---
st.markdown("<h1 style='text-align: center; color: #1e3a8a;'>B-Balance.tech Portal</h1>", unsafe_allow_html=True)
st.write("---")

col_input, col_output = st.columns([1, 3], gap="large")

with col_input:
    st.subheader("📥 Data Input")
    st.caption("Excel에서 [일련번호  크기  위상] 순으로 복사해 붙여넣으세요.")
    raw_input = st.text_area("Input Area", height=400, placeholder="C1ZP01 211522.8 0.0\nC1ZP02 211621.1 3.9...")
    
    parsed = []
    if raw_input.strip():
        for line in raw_input.strip().split('\n'):
            parts = line.replace('\t', ' ').split()
            if len(parts) == 3: # 시리얼 포함
                parsed.append([parts[0], float(parts[1]), float(parts[2])])
            elif len(parts) == 2: # 크기, 위상만
                parsed.append([None, float(parts[0]), float(parts[1])])
    
    df = pd.DataFrame(parsed, columns=['Serial', 'Magnitude', 'Phase'])

with col_output:
    if not df.empty:
        mag, ang = calculate_analysis(df)
        
        # 상단 대형 지표
        st.markdown(f"""
            <div style="background-color: white; padding: 30px; border-radius: 15px; border: 2px solid #e2e8f0; text-align: center;">
                <p style="color: #64748b; margin: 0;">Total Resultant Unbalance</p>
                <h1 style="color: #1e40af; font-size: 4em; margin: 0;">{mag:.6f}</h1>
                <p style="font-size: 1.2em;">at <b>{ang:.2f}°</b></p>
            </div>
        """, unsafe_allow_html=True)

        c_chart, c_report = st.columns([2, 1])
        
        with c_chart:
            fig = go.Figure()
            for _, row in df.iterrows():
                fig.add_trace(go.Scatterpolar(r=[0, row['Magnitude']], theta=[0, row['Phase']], mode='lines', line=dict(color='rgba(148, 163, 184, 0.2)', width=1), showlegend=False))
            fig.add_trace(go.Scatterpolar(r=[0, mag], theta=[0, ang], mode='lines+markers', line=dict(color='#ef4444', width=5), name='Resultant'))
            fig.update_layout(polar=dict(angularaxis=dict(rotation=90, direction="counterclockwise")), height=500)
            st.plotly_chart(fig, use_container_width=True)
            
        with c_report:
            st.subheader("📊 Report & Action")
            st.write(f"**Detected Blades:** {len(df)}")
            
            # PDF 생성 및 다운로드 버튼
            pdf_data = generate_pdf(df, mag, ang)
            st.download_button(
                label="📥 Download PDF Report",
                data=pdf_data,
                file_name=f"B-Balance_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                mime="application/pdf"
            )
            
            st.markdown("---")
            st.info("전문적인 최적화 배열표가 필요하시면 아래 버튼을 눌러 의뢰하세요.")
            mail_link = f"mailto:whynot0926@gmail.com?subject=[Request] Optimization&body=Resultant: {mag:.6f}"
            st.markdown(f'<a href="{mail_link}"><button style="width:100%; height:50px; background-color:#1e40af; color:white; border:none; border-radius:10px; cursor:pointer;">Order Professional Service</button></a>', unsafe_allow_html=True)
    else:
        st.info("좌측 입력창에 데이터를 입력하면 분석 결과와 PDF 리포트가 생성됩니다.")